### ISSUE TITLE
ApiHeaders default value when enum is not working

### ISSUE THREAD

**Issue by renatarussar** [nestjs/swagger#1068]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior
I want to set a default value to one of my headers property using ApiHeaders decorator.
The property is of enum type.
But it doesn't show on the page with the default.

## Expected behavior
The code should generate the following output:
```
        - name: Authorization-Provider
          in: header
          description: Authorization provider identifier
          required: false
          schema:
            enum:
              - RHSSO
              - OAM
            type: string
            default: OAM
```
But today it is not generating the `default` configuration.

## Minimal reproduction of the problem with instructions
```
  @ApiHeaders([
    {
      name: 'Authorization-Provider',
      description: 'Authorization provider identifier',
      required: false,
      schema: {
        default: AuthorizationProviderEnum.OAM
      },
      enum: AuthorizationProviderEnum
    }
  ])
```

## Environment

<pre><code>
"@nestjs/swagger": "^4.7.5"
"@nestjs/core": "^7.5.5"
 
For Tooling issues:
- Node version: v12.18.3  
- Platform:  Mac
</code></pre>
