### ISSUE TITLE
Nullable Enum not generated as nullable

### ISSUE THREAD

**Issue by jbdemonte** [nestjs/swagger#1889]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Using the following annotation:
```typescript
export class ClientResponseDto {
  @Expose()
  @ApiProperty({ enum: PaymentTermsEnum, enumName: 'PaymentTermsEnum', nullable: true })
  paymentTerms!: PaymentTermsEnum | null;

}
```
`openapi-generator 5.4` generates:

```typescript
export interface GetClientByIdResponseDto { 
    paymentTerms: PaymentTermsEnum;
```

I need to use the following workaround to get it nullable:

```typescript
export class ClientResponseDto {
  @Expose()
  @ApiProperty({ oneOf: [{ type: 'enum', $ref: 'PaymentTermsEnum', nullable: true }] })
  paymentTerms!: PaymentTermsEnum | null;
}
```

=> 
```typescript

export interface GetClientByIdResponseDto {
    paymentTerms: PaymentTermsEnum | null;
}
```

### Minimum reproduction code

https://github.com/jbdemonte/issue-nestjs-openapi-generator-nullable-enum

### Steps to reproduce

1.  `npm install`
2.  `npm run generate:angular-client`

### Expected behavior

the exported `value` type should be `value!: FooBarEnum | null;`

### Package version

5.2.1

### NestJS version

8.4.4

### Node.js version

16.13.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/swagger/pull/2051

**Comment by milo526** [comment]
Can we re-open this issue?

The problem is still present in the latest version of this library, and the linked merge request is closed.

**Comment by kamilmysliwiec** [comment]
This should be fixed in newer versions of the library. Could you create a separate issue and provide a minimum reproduction repository?

**Comment by mothershipper** [comment]
We're also experiencing this issue on the latest version of the library. 

The problem is that when you name the enum, Nest is extracting the enum into a shared type (with`$ref`), but leaving the `nullable: true` on the property rather than the shared type:

```yaml
objects:
  Enum:
    type: string
    values:
      - One
      - Two
  MyApiObj:
    properties:
       someField:
         $ref: objects/Enum
         nullable: true
```

OpenAPI treats `$ref` as a replace operation rather than merge, so `nullable: true` is lost. 

If you don't supply a name to the `ApiProperty` decorator, Nest doesn't extract the enum definition into a separate type, declaring it inline so `nullable: true` is preserved.  While this works, it also means code-generators generate worse names for the enum. 

It looks like Nest added support for the nest compiler to generate unnamed nullable enum types as described above, but not named types. Though, if the named enum is used in difference contexts (one nullable, one not) you really can't extract to a shared named type, unless using OpenAPI 3.1.x semantics for nullable properties, i.e.

```yaml
objects:
  Enum:
    type: string
    values:
      - One
      - Two
  MyApiObj:
    properties:
       someField:
         oneOf:
           - $ref: objects/Enum
           - type: nullable
```
