### ISSUE TITLE
Serverless issue

### ISSUE THREAD

**Issue by csakbalint** [nestjs/swagger#199]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior

Swagger endpoint is not found.

## Expected behavior

Html response generated by swagger-ui.

## Minimal reproduction of the problem with instructions

Here is an [example](https://gist.github.com/csakbalint/7fe406bd1b15124180a988c87d57cf9b)  I use in my project.

## What is the motivation / use case for changing the behavior?

I'd like to generate swagger documents based on my modules and endpoints, but I cannot.

## Environment

<pre><code>
"@nestjs/common": "^5.4.0",
"@nestjs/core": "^5.4.0",
"@nestjs/swagger": "^2.5.1",
"aws-serverless-express": "^3.3.5",
"express": "^4.16.4",

 
For Tooling issues:
- Node version: 8.10  
- Platform: Mac 

Others:
I run my environment with serverless and serverless-offline plugin

</code></pre>

**Comment by jtmthf** [comment]
@csakbalint I just ran into this the other day. The problem is that given a swagger path of `swagger`, swagger-ui-express serves its html file from `/swagger/` and will redirect if the request path is `/swagger`. Unfortunately API Gateway strips the trailing slash from the request path so you have to add it back with the block below.

```ts
if (event.path === '/swagger') {
  event.path = '/swagger/';
}
```

This cannot be done as a middleware as `req.path` from express is a getter and will throw an error if you try to overwrite it.

**Comment by plorencrstit** [comment]
I have the similar problem. Swagger documentation doesn't work on AWS lambda using serverless framework. It works testing it locally (`sls offline start`). 

What is very strange, that only one file .js and doesn't have 404. Others does. I have no idea why.

Swagger API documentation:
https://js6bdk1qg3.execute-api.eu-west-2.amazonaws.com/master/api

404:
https://js6bdk1qg3.execute-api.eu-west-2.amazonaws.com/master/swagger-ui-bundle.js

200:
https://js6bdk1qg3.execute-api.eu-west-2.amazonaws.com/master/swagger-ui-init.js

My part of configuration:
```
  if (event.path === '/api') {
    event.path = '/api/';
  }

event.path = event.path.includes('swagger-ui') ? `/api${event.path}` : event.path;
```

```
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';

export default (app, isServerless = false): void => {
  const serverUrl = isServerless ? '/dev' : '/';

  const options = new DocumentBuilder()
    .setTitle(process.env.APP_NAME)
    .setDescription(process.env.APP_DESC)
    .setVersion('1.0')
    .addServer(serverUrl)
    .addBearerAuth()
    .build();

  const document = SwaggerModule.createDocument(app, options);

  SwaggerModule.setup('api', app, document);
};
```

@jtmthf @csakbalint would you have any idea?

**Comment by NastyZ98** [comment]
Hi @plorencrstit , I am trying to use swagger with serverless and lambda functions.
Can you explain how did you configure it ?

**Comment by plorencrstit** [comment]
Hi @NastyZ98, 
what problem do you have?

Using TS and `serverless-plugin-optimize` plugin I needed to add to my `serverless.yml` configuration:
```
custom:
  optimize:
    external: ['swagger-ui-dist']
```

in  `lambda.ts`: [my handler]

```
export const handler: Handler = async (event: any, context: Context) => {
  if (event.path === '/api') {
    event.path = '/api/';
  }
  event.path = event.path.includes('swagger-ui') ? `/api${event.path}` : event.path;

  cachedServer = await bootstrapServer();

  return proxy(cachedServer, event, context, 'PROMISE').promise;
};
```

**Comment by NastyZ98** [comment]
@plorencrstit hi, thank you for your reply,
I am trying to make swagger working on my aws lambda but it result of a 404 with `sls offline` and of an error 500 when I deploy on aws.

I also added `serverless-plugin-optimize` and edited my `serverless.yml` but it looks like that `serverless-plugin-optimize` broke something when I call: `myawsurl/dev/api`

<img width="835" alt="Capture d’écran 2020-04-22 à 00 59 17" src="https://user-images.githubusercontent.com/7148684/79922811-9919eb80-8434-11ea-81a4-53f31edb77c4.png">

Here is my `lambda.ts`
```ts
const binaryMimeTypes: string[] = [];

let cachedServer: Server;

process.on('unhandledRejection', reason => {
  console.error(reason);
});

process.on('uncaughtException', reason => {
  console.error(reason);
});

function setupSwagger(app: INestApplication) {
  const options = new DocumentBuilder()
    .setTitle('Tyffis API')
    .setDescription('Tyffis REST API documentation')
    .setVersion('1.0.0')
    .addTag('tyffis')
    .build();
  const document = SwaggerModule.createDocument(app, options);
  SwaggerModule.setup('api', app, document);
}

async function bootstrapServer(): Promise<Server> {
  if (!cachedServer) {
    try {
      const expressApp = express();
      const adapter = new ExpressAdapter(expressApp);
      const nestApp = await NestFactory.create(AppModule, adapter);
      nestApp.use(eventContext());
      await nestApp.init();
      setupSwagger(nestApp);
      cachedServer = createServer(expressApp, undefined, binaryMimeTypes);
    } catch (error) {
      return Promise.reject(error);
    }
  }
  return Promise.resolve(cachedServer);
}

export const handler: Handler = async (event: any, context: Context) => {
  if (event.path === '/api') {
    event.path = '/api/';
  }
  event.path = event.path.includes('swagger-ui')
    ? `/api${event.path}`
    : event.path;

  cachedServer = await bootstrapServer();
  return proxy(cachedServer, event, context, 'PROMISE').promise;
};
```

**Comment by plorencrstit** [comment]
I had the same problem before with `typeorm`. My solution was to manually listed entities in the configuration file. So I have two kind of settings.

```export const typeOrmConfig: TypeOrmModuleOptions = {
  entities: [`${__dirname}/../**/*.entity{.ts,.js}`],
  ...typeOrmConfigGeneral,
};

export const typeOrmConfigServerless: TypeOrmModuleOptions = {
  entities: [
    Category,
    Comment,
    Discussion,
  ],
  ...typeOrmConfigGeneral,
};
```
I choose the configuration based on some `env`. 

Do you use `typeorm`?

**Comment by NastyZ98** [comment]
Yes I use typeorm, your solution have fixed my problem concerning the entity :) ! But my swagger documentation still don't work..

![Capture d’écran 2020-04-22 à 10 46 53](https://user-images.githubusercontent.com/7148684/79961256-b9729600-8486-11ea-988d-05d0b2b875b5.png)

Here is my `serverless.yml`

```yml
functions:
  index:
    handler: src/lambda.handler
    events:
      - http:
          cors: true
          path: '/{proxy+}'
          method: any
```

Did I miss something in my `lambda.ts`upper ?

**Comment by plorencrstit** [comment]
Show the entire `serverless.yml`, please.

**Comment by NastyZ98** [comment]
Here it is: 

```yml
service: tyffis-backend-test

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  role: LambdaRole
  memorySize: 512
  vpc:
    securityGroupIds:
      - sg
    subnetIds:
      - ids
  environment:
    TYPEORM_HOST: ${self:custom.AURORA.HOST}
    TYPEORM_PORT: ${self:custom.AURORA.PORT}
    TYPEORM_USER: ${self:custom.USERNAME}
    TYPEORM_PASSWORD: ${self:custom.PASSWORD}
    TYPEORM_DB: ${self:custom.DB_NAME}
    JWT_SECRET: secret

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-offline

package:
  individually: true

custom:
  DB_NAME: db_name
  USERNAME: user
  PASSWORD: pwd
  AURORA:
    HOST:
      Fn::GetAtt: [AuroraRDSCluster, Endpoint.Address]
    PORT:
      Fn::GetAtt: [AuroraRDSCluster, Endpoint.Port]
  optimize:
    external: ['swagger-ui-dist']

resources:
  Resources:
    LambdaRole: ${file(./infra-serverless/LambdaRole.yml)}
    AuroraRDSCluster: ${file(./infra-serverless/AuroraRDSCluster.yml)}

functions:
  index:
    handler: src/lambda.handler
    events:
      - http:
          cors: true
          path: '/{proxy+}'
          method: any
```

**Comment by plorencrstit** [comment]
Try with:
```
functions:
  main:
    handler: src/lambda.handler
    events:
      - http:
          method: any
          path: /{any+}
```
