### ISSUE TITLE
Allow parameter to be shared

### ISSUE THREAD

**Issue by drewish** [nestjs/swagger#2731]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I'd like to avoid having to repeatedly define a parameter that's shared between several routes in a controller:
```ts
    @ApiParam({
        name: 'entryId',
        description: `The auditor's entryId.`,
    })
```

In a raw OpenAPI file I could just define a parameter component:
```yaml
components:
   parameters:
      entryParam:
         name: entryId
         in: query
         description: The auditor's entryId.
         required: true
```
And then reference it from the path:
```yaml
paths:
   /path:
      get:
         parameters:
            - $ref: "#/components/parameters/entryParam"
```

### Describe the solution you'd like

I think we could add a new method on the DocumentBuilder to define the parameter definition:
```ts
const options = new DocumentBuilder()
    // ...
    .addParameters({
        name: 'entryId',
        in: 'query',
        description: "The auditor's entryId.",
    })
```
And then reference it using the annotation:
```ts
    @ApiParam({
        $ref: '#/components/parameters/entryParam`,
    })
```

### What is the motivation / use case for changing the behavior?

This would allow parameter definitions to be shared between multiple routes or controllers. Centralized definitions will be consistent and can be quickly updated. The route definitions are more readable when they aren't cluttered up with repeated parameter definitions.
