### ISSUE TITLE
@ApiHeader() schema is being overwritten if an enum is provided

### ISSUE THREAD

**Issue by jointhejourney** [nestjs/swagger#2761]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Using the following @ApiHeader() with an enum:

```ts
  @ApiHeader({
    name: 'Journey-Version',
    description: 'API version',
    enum: ['1'],
    schema: {
      default: '1',
    }
  })
```

Generates the following OpenAPI schema:

```yaml
 /test:
    post:
      operationId: TestController_testRequest
      parameters:
        - name: Journey-Version
          in: header
          description: Journey API version.
          required: false
          schema:
            enum:
              - '1'
            type: string
```

### Minimum reproduction code

https://gist.github.com/jointhejourney/13b4cd7feba0864f11c8fd42fd069890

### Expected behavior

It should include the default value as provided by the schema, such as:

```yaml
 /test:
    post:
      operationId: TestController_testRequest
      parameters:
        - name: Journey-Version
          in: header
          description: Journey API version.
          required: false
          schema:
            type: string
            enum:
              - '1'
            default: '1'
```

### Package version

7.1.10

### NestJS version

9.3.9

### Node.js version

18.19.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

This seems to be a fairly straightforward fix, the schema is being overwritten here if an enum is provided:

https://github.com/nestjs/swagger/blob/5108ba6c2fa9e10326bb36dedf2a45c8e3a9d48d/lib/decorators/api-header.decorator.ts#L36-L42

Maybe we can do it like this?

```diff
  if (options.enum) {
    const enumValues = getEnumValues(options.enum);
    param.schema = {
+     ...param.schema,
      enum: enumValues,
      type: getEnumType(enumValues)
    };
  }
```

This way, if a default value is provided in the schema object, it won't be ignored. This is a not a huge issue since I can just provide the enum directly into the schema, but if my suggestion makes sense, I could submit a PR. Thanks!
