### ISSUE TITLE
Array schemas are not generated properly

### ISSUE THREAD

**Issue by ccaspers** [nestjs/swagger#3207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When an array is declared, depending on where its used and how it was decorated, the output doesn't look as one would expect.

- the array type is sometimes not rendered correctly
- restrictions on array-length are missing 
- restrictions on the length of strings in a string array are missing 

### Minimum reproduction code

https://github.com/ccaspers/nestjs-swagger/commit/3248507c5c40abc7623cdee6663a50fc1e68bf1e

### Steps to reproduce

1. `git clone git@github.com:ccaspers/nestjs-swagger.git`
2. `cd nestjs-swagger`
3. `git switch array-schemas-bug`
4. `npm i`
5. `npm run test`

### Expected behavior

all tests succeed

### Package version

8.1.0

### NestJS version

10.4.15

### Node.js version

20.12.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

Maybe the syntax used in some of the decorators is wrong? But there is no documentation with regards to how things should not be declared.

Also, at least in the case for dtos for query parameters, there is no combination of syntax available that leads to the desired result.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by kamilmysliwiec** [comment]
They look reasonable yes

**Comment by mag123c** [comment]
@ccaspers Hello, If you are not working on it, can I create this PR?

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/swagger/pull/3218

**Comment by ccaspers** [comment]
I checked #3218 but it will not work as expected. I have something that works and that makes the unit tests I created succeed. The changes feel extremely hacky right now. 

I'll try to improve on this when I find the time. Current state of my changes can be checked here
https://github.com/nestjs/swagger/compare/master...ccaspers:nestjs-swagger:array-schemas-bug

**Comment by ccaspers** [comment]
@kamilmysliwiec maybe it makes sense to reopen this issue, since it is related to #3218 but not identical

**Comment by jdespatis** [comment]
@ccaspers I experience the same problem as you,

for example in a dto containing:

```typescript
  @MinLength(3, { each: true })
  @IsString({ each: true })
  values: string[];
```

The NestJS Swagger plugin generates this:

```yaml
        - name: values
          required: false
          in: query
          schema:
            minLength: 3
            type: array
            items:
              type: string
````

instead of this:

```yaml
        - name: values
          required: false
          in: query
          schema:
            type: array
            items:
              type: string
              minLength: 3
```

=> the `each: true` setting doesn't seem to be considered

@kamilmysliwiec It may make sense to reopen this issue, don't you think?
