### ISSUE TITLE
OpenApi generation strips away DTO  title and description

### ISSUE THREAD

**Issue by yohny** [nestjs/swagger#3309]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behavior

I have a DTO specified usinng Zod like so:
```ts
const aZodExtendedSchema = extendApi(
  z.object({
    uid: extendApi(z.string().nonempty(), {
      title: "Unique ID",
      description: "A UUID generated by the server",
    }),
    firstName: z.string().min(2),
    lastName: z.string().optional(),
    email: z.string().email(),
    phoneNumber: extendApi(z.string().min(10), {
      description: "US Phone numbers only",
      example: "555-555-5555",
    }),
  }),
  {
    title: "User",
    description: "A user schema",
  },
);

export class UserDto extends createZodDto(aZodExtendedSchema) {}
```
and when I log the produced schema using `console.log(generateSchema(aZodExtendedSchema))` it looks as expected (including specified DTO title and description):
```js
{
  type: [ 'object' ],
  properties: {
    uid: {
      type: [Array],
      minLength: 1,
      title: 'Unique ID',
      description: 'A UUID generated by the server'
    },
    firstName: { type: [Array], minLength: 2 },
    lastName: { type: [Array] },
    email: { type: [Array], format: 'email' },
    phoneNumber: {
      type: [Array],
      minLength: 10,
      description: 'US Phone numbers only',
      example: '555-555-5555'
    }
  },
  required: [ 'uid', 'firstName', 'email', 'phoneNumber' ],
  title: 'User', // title present
  description: 'A user schema' // description present
}
```
however when I generate the OpenApi specification using
```ts
const document = new DocumentBuilder()
    .setTitle("Some title")
    .setDescription("Some description")
    .build();
```
the resulting `schemas:` section does not contain specified DTO title or description
```yaml
components:
  schemas:
    UserDto:
      type: object
      properties:
        uid:
          type: string
          minLength: 1
          title: Unique ID
          description: A UUID generated by the server
        firstName:
          type: string
          minLength: 2
        lastName:
          type: string
        email:
          type: string
          format: email
        phoneNumber:
          type: string
          minLength: 10
          description: US Phone numbers only
          example: 555-555-5555
      required:
        - uid
        - firstName
        - email
        - phoneNumber
```

### Minimum reproduction code

provided in description above

### Expected behavior

the specified title and description should be present in generated OpenApi schema

### Package version

7.3.1

### NestJS version

10.3.7

### Node.js version

20.18.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [x] Linux
