### ISSUE TITLE
nullable doesn't seem to be implemented properly

### ISSUE THREAD

**Issue by hfhchan-plb** [nestjs/swagger#3367]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behavior

`nullable` seems to be directly spit out in the generated JSON, but OpenAPI is expecting `type` to be an array which includes the value "null".

### Minimum reproduction code

https://example.org

### Steps to reproduce

```ts
export class InfoDTO {
  @ApiProperty({ type: String, nullable: true })
  propertyName: string | null
}
```

generates:

```yaml
    InfoDTO:
      type: object
      properties:
        propertyName:
          type: string
          nullable: true
```

### Expected behavior

```yaml
    InfoDTO:
      type: object
      properties:
        propertyName:
          type: ['string', 'null']
```

### Package version

8.1.0

### NestJS version

10.4.15

### Node.js version

20.10.0

### In which operating systems have you tested?

- [x] macOS
- [ ] Windows
- [ ] Linux
